// Frameworks/retirement-calculator-angular/src/app/app.component.ts
// File: src/app/app.component.ts

// This tells TypeScript that 'corticonEngine' is a global variable
// that will be available at runtime.
declare const corticonEngine: any;

import { Component, OnInit } from '@angular/core';
// Import CommonModule for pipes and directives like *ngIf, and FormsModule for [(ngModel)].
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-root',
  standalone: true, // Mark the component as standalone
  imports: [
    CommonModule, // Import for common directives and pipes
    FormsModule   // Import for two-way data binding with [(ngModel)]
  ],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  // The 'inputs' object holds all the data bound to our form fields.
  inputs = {
    dateOfBirth: "1993-11-05",
    annualPreTaxIncome: 60000,
    currentRetirementSavings: 30000,
    monthlyContributions: 500,
    otherMonthlyRetirementIncome: 0,
    ageOfRetirement: 67,
    lifeExpectancy: 95,
    preRetirementRateOfReturn: 6,
    postRetirementRateOfReturn: 5,
    inflationRate: 3,
    annualIncomeIncrease: 2,
    monthlyBudgetInRetirement: 70
  };

  // These properties will hold the state of our application (the results, loading status, and any errors).
  results: any = null;
  isLoading = false;
  error: string | null = null;

  // ngOnInit is a lifecycle hook that runs once when the component is first initialized.
  ngOnInit() {
    // We try to load any previously saved inputs from the user's browser.
    try {
      const savedInputs = localStorage.getItem('angularRetirementInputs');
      if (savedInputs) {
        this.inputs = JSON.parse(savedInputs);
      }
    } catch (e) {
      console.warn('Could not restore inputs from localStorage.');
    }
  }

  // This is the main function that gets called when the form is submitted.
  // It's 'async' because it needs to 'await' the result from the Corticon engine.
  async calculate() {
    this.isLoading = true;
    this.error = null;
    this.results = null;
    localStorage.setItem('angularRetirementInputs', JSON.stringify(this.inputs));

    // We build the payload object in the exact format the decision service expects.
    const payload = [{
      "#type": "Individual",
      ...this.inputs,
      // We must convert the percentage values from the form (e.g., 6) to decimals (e.g., 0.06).
      preRetirementRateOfReturn: this.inputs.preRetirementRateOfReturn / 100,
      postRetirementRateOfReturn: this.inputs.postRetirementRateOfReturn / 100,
      inflationRate: this.inputs.inflationRate / 100,
      annualIncomeIncrease: this.inputs.annualIncomeIncrease / 100,
      monthlyBudgetInRetirement: this.inputs.monthlyBudgetInRetirement / 100,
    }];

    // We call the Corticon engine and handle the results.
    try {
      const result = await corticonEngine.execute(payload, { logLevel: 0 });

      if (result && result.payload && result.corticon.status === 'success') {
        this.results = result.payload.find((obj: any) => obj['#type'] === 'Individual');
      } else {
        this.error = result?.corticon?.messages?.[0]?.text || "An unknown error occurred.";
        console.error("Corticon error details:", result);
      }
    } catch (e: any) {
      this.error = `An unexpected JavaScript error occurred: ${e.message}`;
      console.error(e);
    }
    this.isLoading = false;
  }

  // A simple helper function to make sure numbers are formatted correctly for the template.
  formatNumber(num: any): number {
    return parseFloat(num);
  }
}
<!-- File: src/app/app.component.html -->

<main class="container">
  <h1>Retirement Calculator (Angular)</h1>
  <!-- The (ngSubmit) event calls our calculate() function. -->
  <!-- We use [(ngModel)] for two-way data binding between the form inputs and our 'inputs' object. -->
  <form (ngSubmit)="calculate()">
    <div class="grid">
      <label>Date of Birth:<input type="date" [(ngModel)]="inputs.dateOfBirth" name="dateOfBirth"></label>
      <label>Annual Pre-Tax Income:<input type="number" [(ngModel)]="inputs.annualPreTaxIncome"
          name="annualPreTaxIncome" step="1000"></label>
    </div>
    <div class="grid">
      <label>Current Retirement Savings:<input type="number" [(ngModel)]="inputs.currentRetirementSavings"
          name="currentRetirementSavings" step="1000"></label>
      <label>Monthly Contributions ($):<input type="number" [(ngModel)]="inputs.monthlyContributions"
          name="monthlyContributions" step="50"></label>
    </div>
    <div class="grid">
      <label>Other Monthly Retirement Income ($):<input type="number" [(ngModel)]="inputs.otherMonthlyRetirementIncome"
          name="otherMonthlyRetirementIncome" step="50"></label>
    </div>

    <details>
      <summary>Advanced Details</summary>
      <div class="grid grid-3">
        <label>Retirement Age:<input type="number" [(ngModel)]="inputs.ageOfRetirement" name="ageOfRetirement"></label>
        <label>Life Expectancy:<input type="number" [(ngModel)]="inputs.lifeExpectancy" name="lifeExpectancy"></label>
      </div>
      <div class="grid grid-3">
        <label>Pre-Retirement Return (%):<input type="number" [(ngModel)]="inputs.preRetirementRateOfReturn"
            name="preRetirementRateOfReturn" step="0.1"></label>
        <label>Post-Retirement Return (%):<input type="number" [(ngModel)]="inputs.postRetirementRateOfReturn"
            name="postRetirementRateOfReturn" step="0.1"></label>
        <label>Inflation Rate (%):<input type="number" [(ngModel)]="inputs.inflationRate" name="inflationRate"
            step="0.1"></label>
      </div>
      <div class="grid grid-3">
        <label>Annual Income Increase (%):<input type="number" [(ngModel)]="inputs.annualIncomeIncrease"
            name="annualIncomeIncrease" step="0.1"></label>
        <label>Retirement Budget (% of Income):<input type="number" [(ngModel)]="inputs.monthlyBudgetInRetirement"
            name="monthlyBudgetInRetirement" step="1"></label>
      </div>
    </details>

    <!-- The button is disabled and shows a loading state while 'isLoading' is true. -->
    <button type="submit" [attr.aria-busy]="isLoading" [disabled]="isLoading"
      style="margin-top: 1rem;">Calculate</button>
  </form>

  <!-- This section conditionally displays the results, loading state, or error messages. -->
  <div style="margin-top: 2rem;">
    <article *ngIf="isLoading" aria-busy="true"></article>
    <article *ngIf="error" style="background-color: var(--pico-form-element-invalid-background-color)">
      <strong>Error:</strong> {{ error }}</article>
    <section *ngIf="results">
      <h2>Results</h2>
      <!-- We use Angular's built-in 'currency' pipe for easy formatting. -->
      <p><strong>What you'll have:</strong> {{ formatNumber(results.estimatedSavingsAtRetirement) |
        currency:'USD':'symbol':'1.0-0' }}</p>
      <p><strong>What you'll need:</strong> {{ formatNumber(results.targetRetirementSavings) |
        currency:'USD':'symbol':'1.0-0' }}</p>
      <div *ngIf="results.guidance && results.guidance.length > 0">
        <h3>Guidance:</h3>
        <ul>
          <li *ngFor="let g of results.guidance">{{ g.content }}</li>
        </ul>
      </div>
      <details>
        <summary>Show Calculation Details</summary>
        <!-- The 'json' pipe is a handy way to display the raw data for debugging. -->
        <pre><code>{{ results | json }}</code></pre>
      </details>
    </section>
  </div>
</main>

// Frameworks/retirement-calculator-vue/src/App.vue
<script setup>
import { reactive, ref, onMounted } from 'vue';

// This component assumes that `window.corticonEngine` is globally available
// from the script tag included in the main index.html file.

// State management using Vue's Composition API
const inputs = reactive({
    dateOfBirth: "1993-11-05",
    annualPreTaxIncome: 60000,
    currentRetirementSavings: 30000,
    monthlyContributions: 500,
    otherMonthlyRetirementIncome: 0,
    ageOfRetirement: 67,
    lifeExpectancy: 95,
    preRetirementRateOfReturn: 6,
    postRetirementRateOfReturn: 5,
    inflationRate: 3,
    annualIncomeIncrease: 2,
    monthlyBudgetInRetirement: 70
});
const results = ref(null);
const isLoading = ref(false);
const error = ref(null);

// Lifecycle hook to load data when the component is mounted
onMounted(() => {
    try {
        const savedInputs = localStorage.getItem('vueRetirementInputs');
        if (savedInputs) {
            Object.assign(inputs, JSON.parse(savedInputs));
        }
    } catch (e) {
        console.warn('Could not restore inputs from localStorage.');
    }
});

// Main calculation logic
const calculate = async () => {
    isLoading.value = true;
    error.value = null;
    results.value = null;
    localStorage.setItem('vueRetirementInputs', JSON.stringify(inputs));

    const payload = [{
        "#type": "Individual",
        dateOfBirth: inputs.dateOfBirth,
        annualPreTaxIncome: inputs.annualPreTaxIncome,
        currentRetirementSavings: inputs.currentRetirementSavings,
        monthlyContributions: inputs.monthlyContributions,
        otherMonthlyRetirementIncome: inputs.otherMonthlyRetirementIncome,
        ageOfRetirement: inputs.ageOfRetirement,
        lifeExpectancy: inputs.lifeExpectancy,
        preRetirementRateOfReturn: inputs.preRetirementRateOfReturn / 100,
        postRetirementRateOfReturn: inputs.postRetirementRateOfReturn / 100,
        inflationRate: inputs.inflationRate / 100,
        annualIncomeIncrease: inputs.annualIncomeIncrease / 100,
        monthlyBudgetInRetirement: inputs.monthlyBudgetInRetirement / 100,
    }];
    
    try {
        const result = await window.corticonEngine.execute(payload, { logLevel: 0 });
        if (result && result.payload && result.corticon.status === 'success') {
            results.value = result.payload.find(obj => obj['#type'] === 'Individual');
        } else {
            error.value = result?.corticon?.messages?.[0]?.text || "An unknown error occurred during rule execution.";
            console.error("Corticon error details:", result);
        }
    } catch (e) {
        error.value = `An unexpected JavaScript error occurred: ${e.message}`;
        console.error(e);
    }
    isLoading.value = false;
};

// Formatting helper for currency display
const formatNumber = (num) => {
    if (typeof num === 'number' || (typeof num === 'string' && num.length > 0)) {
        return parseFloat(num).toLocaleString(undefined, { maximumFractionDigits: 0 });
    }
    return '0';
};
</script>

<template>
  <main class="container">
    <h1>Retirement Calculator (Vue.js)</h1>
    <form @submit.prevent="calculate">
      <div class="grid">
        <label>Date of Birth:<input type="date" v-model="inputs.dateOfBirth"></label>
        <label>Annual Pre-Tax Income:<input type="number" v-model.number="inputs.annualPreTaxIncome" step="1000"></label>
      </div>
      <div class="grid">
        <label>Current Retirement Savings:<input type="number" v-model.number="inputs.currentRetirementSavings" step="1000"></label>
        <label>Monthly Contributions ($):<input type="number" v-model.number="inputs.monthlyContributions" step="50"></label>
      </div>
      <div class="grid">
        <label>Other Monthly Retirement Income ($):<input type="number" v-model.number="inputs.otherMonthlyRetirementIncome" step="50"></label>
      </div>

       <details>
          <summary>Advanced Details</summary>
          <div class="grid grid-3">
              <label>Retirement Age:<input type="number" v-model.number="inputs.ageOfRetirement"></label>
              <label>Life Expectancy:<input type="number" v-model.number="inputs.lifeExpectancy"></label>
          </div>
          <div class="grid grid-3">
              <label>Pre-Retirement Return (%):<input type="number" v-model.number="inputs.preRetirementRateOfReturn" step="0.1"></label>
              <label>Post-Retirement Return (%):<input type="number" v-model.number="inputs.postRetirementRateOfReturn" step="0.1"></label>
              <label>Inflation Rate (%):<input type="number" v-model.number="inputs.inflationRate" step="0.1"></label>
          </div>
          <div class="grid grid-3">
              <label>Annual Income Increase (%):<input type="number" v-model.number="inputs.annualIncomeIncrease" step="0.1"></label>
              <label>Retirement Budget (% of Income):<input type="number" v-model.number="inputs.monthlyBudgetInRetirement" step="1"></label>
          </div>
      </details>

      <button type="submit" :aria-busy="isLoading" :disabled="isLoading" style="margin-top: 1rem;">Calculate</button>
    </form>

    <div style="margin-top: 2rem;">
      <article v-if="isLoading" aria-busy="true"></article>
      <article v-if="error" style="background-color: var(--pico-form-element-invalid-background-color)"><strong>Error:</strong> {{ error }}</article>
      <section v-if="results">
        <h2>Results</h2>
        <p><strong>What you'll have:</strong> ${{ formatNumber(results.estimatedSavingsAtRetirement) }}</p>
        <p><strong>What you'll need:</strong> ${{ formatNumber(results.targetRetirementSavings) }}</p>
        <div v-if="results.guidance && results.guidance.length > 0">
          <h3>Guidance:</h3>
          <ul>
            <li v-for="(g, index) in results.guidance" :key="index">{{ g.content }}</li>
          </ul>
        </div>
        <details>
            <summary>Show Calculation Details</summary>
            <pre><code>{{ JSON.stringify(results, null, 2) }}</code></pre>
        </details>
      </section>
    </div>
  </main>
</template>

<style>
  /* You can add global styles here or in a separate CSS file */
  .container {
    max-width: 800px;
    margin: 2rem auto;
    padding: 1rem;
  }
  .grid-3 {
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  }
  details {
      border: 1px solid var(--pico-muted-border-color);
      padding: 1rem;
      border-radius: var(--pico-border-radius);
      margin-top: 1rem;
  }
  summary {
      font-weight: bold;
      cursor: pointer;
  }
</style>
